<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 4.1.0-dev (doctrine2-zf2inputfilterannotation dev) on 2025-12-27
 * 14:17:51.
 * Goto https://bit.ly/mwbexporter for more information.
 */

namespace Base\Entity;

use Doctrine\ORM\Mapping as ORM;
use Laminas\InputFilter\InputFilter;
use Laminas\InputFilter\Factory as InputFactory;
use Laminas\InputFilter\InputFilterAwareInterface;
use Laminas\InputFilter\InputFilterInterface;

/**
 * Base\Entity\News
 *
 *  * 最新消息
 *  *
 * @ORM\Entity(repositoryClass="NewsRepository")
 * @ORM\Table(name="news",
 *     options={"comment": "最新消息",
 *         "collate": "utf8mb4_unicode_ci",
 *         "charset": "utf8mb4"
 *     }
 * )
 */
class News implements InputFilterAwareInterface
{
    /**
     * Instance of InputFilterInterface.
     *
     * @var InputFilter
     */
    private $inputFilter;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * 標題
     * @ORM\Column(type="string", length=100, options={"comment": "標題"})
     */
    protected $title;

    /**
     * 內容
     * @ORM\Column(type="text", options={"comment": "內容"})
     */
    protected $content;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $updated_at;

    /**
     * 公佈狀態
     * @ORM\Column(name="`status`", type="integer", options={"comment": "公佈狀態"})
     */
    protected $status;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param int $id
     * @return \Base\Entity\News
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of title.
     *
     * @param string $title
     * @return \Base\Entity\News
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get the value of title.
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set the value of content.
     *
     * @param string $content
     * @return \Base\Entity\News
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get the value of content.
     *
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set the value of created_at.
     *
     * @param \DateTime $created_at
     * @return \Base\Entity\News
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Get the value of created_at.
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Set the value of updated_at.
     *
     * @param \DateTime $updated_at
     * @return \Base\Entity\News
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Get the value of updated_at.
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Set the value of status.
     *
     * @param int $status
     * @return \Base\Entity\News
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get the value of status.
     *
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Not used, Only defined to be compatible with InputFilterAwareInterface.
     *
     * @param \Laminas\InputFilter\InputFilterInterface $inputFilter
     * @throws \Exception
     */
    public function setInputFilter(InputFilterInterface $inputFilter)
    {
        throw new \Exception("Not used.");
    }

    /**
     * Return a for this entity configured input filter instance.
     *
     * @return InputFilterInterface
     */
    public function getInputFilter()
    {
        if ($this->inputFilter instanceof InputFilterInterface) {
            return $this->inputFilter;
        }
        $factory = new InputFactory();
        $filters = [
            [
                'name' => 'id',
                'required' => false,
                'filters' => [
                                    ['name' => 'Laminas\Filter\ToInt'],
                                ],
                'validators' => [
                                    ['name' => 'Laminas\I18n\Validator\IsInt'],
                                ],
            ],
            [
                'name' => 'title',
                'required' => true,
                'filters' => [
                                    ['name' => 'Laminas\Filter\StripTags'],
                                    ['name' => 'Laminas\Filter\StringTrim'],
                                ],
                'validators' => [
                                    [
                                        'name' => 'Laminas\Validator\StringLength',
                                        'options' => [
                                            'encoding' => 'UTF-8',
                                            'min' => 1,
                                            'max' => 100
                                        ],
                                    ],
                                ],
            ],
            [
                'name' => 'content',
                'required' => true,
                'filters' => [
                                ],
                'validators' => [],
            ],
            [
                'name' => 'created_at',
                'required' => false,
                'filters' => [],
                'validators' => [],
            ],
            [
                'name' => 'updated_at',
                'required' => false,
                'filters' => [],
                'validators' => [],
            ],
            [
                'name' => 'status',
                'required' => true,
                'filters' => [
                                    ['name' => 'Laminas\Filter\ToInt'],
                                ],
                'validators' => [
                                    ['name' => 'Laminas\I18n\Validator\IsInt'],
                                ],
            ],
        ];
        $this->inputFilter = $factory->createInputFilter($filters);

        return $this->inputFilter;
    }

    /**
     * Populate entity with the given data.
     * The set* method will be used to set the data.
     *
     * @param array $data
     * @return boolean
     */
    public function populate(array $data = [])
    {
        foreach ($data as $field => $value) {
            $setter = sprintf('set%s', ucfirst(
                str_replace(' ', '', ucwords(str_replace('_', ' ', $field)))
            ));
            if (method_exists($this, $setter)) {
                $this->{$setter}($value);
            }
        }

        return true;
    }

    /**
     * Return a array with all fields and data.
     * Default the relations will be ignored.
     *
     * @param array $fields
     * @return array
     */
    public function getArrayCopy(array $fields = [])
    {
        $dataFields = ['id', 'title', 'content', 'created_at', 'updated_at', 'status'];
        $relationFields = [];
        $copiedFields = [];
        foreach ($relationFields as $relationField) {
            $map = null;
            if (array_key_exists($relationField, $fields)) {
                $map = $fields[$relationField];
                $fields[] = $relationField;
                unset($fields[$relationField]);
            }
            if (!in_array($relationField, $fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $relationField)))));
            $relationEntity = $this->{$getter}();
            $copiedFields[$relationField] = (!is_null($map))
                ? $relationEntity->getArrayCopy($map)
                : $relationEntity->getArrayCopy();
            $fields = array_diff($fields, [$relationField]);
        }
        foreach ($dataFields as $dataField) {
            if (!in_array($dataField, $fields) && !empty($fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $dataField)))));
            $copiedFields[$dataField] = $this->{$getter}();
        }

        return $copiedFields;
    }

    public function __sleep()
    {
        return ['id', 'title', 'content', 'created_at', 'updated_at', 'status'];
    }
}