<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 4.1.0-dev (doctrine2-zf2inputfilterannotation dev) on 2025-12-27
 * 15:13:40.
 * Goto https://bit.ly/mwbexporter for more information.
 */

namespace Base\Entity;

use Doctrine\ORM\Mapping as ORM;
use Laminas\InputFilter\InputFilter;
use Laminas\InputFilter\Factory as InputFactory;
use Laminas\InputFilter\InputFilterAwareInterface;
use Laminas\InputFilter\InputFilterInterface;

/**
 * Base\Entity\Users
 *
 *  * 使用者
 *  *
 * @ORM\Entity(repositoryClass="UsersRepository")
 * @ORM\Table(name="users",
 *     indexes={@ORM\Index(name="fk_users_auth_role_idx", columns={"auth_role_id"})},
 *     options={"comment": "使用者",
 *         "collate": "utf8mb4_unicode_ci",
 *         "charset": "utf8mb4"
 *     }
 * )
 */
class Users implements InputFilterAwareInterface
{
    /**
     * Instance of InputFilterInterface.
     *
     * @var InputFilter
     */
    private $inputFilter;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $auth_role_id;

    /**
     * 帳號
     * @ORM\Column(type="string", length=45, options={"comment": "帳號"})
     */
    protected $username;

    /**
     * 密碼
     * @ORM\Column(name="`password`", type="string", length=45, options={"comment": "密碼"})
     */
    protected $password;

    /**
     * 狀態
     * @ORM\Column(name="`status`", type="integer", options={"comment": "狀態"})
     */
    protected $status;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity="Base\Entity\AuthRole", inversedBy="users")
     * @ORM\JoinColumn(name="auth_role_id", referencedColumnName="id", nullable=false)
     */
    protected $auth_role;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param int $id
     * @return \Base\Entity\Users
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of auth_role_id.
     *
     * @param int $auth_role_id
     * @return \Base\Entity\Users
     */
    public function setAuthRoleId($auth_role_id)
    {
        $this->auth_role_id = $auth_role_id;

        return $this;
    }

    /**
     * Get the value of auth_role_id.
     *
     * @return int
     */
    public function getAuthRoleId()
    {
        return $this->auth_role_id;
    }

    /**
     * Set the value of username.
     *
     * @param string $username
     * @return \Base\Entity\Users
     */
    public function setUsername($username)
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Get the value of username.
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Set the value of password.
     *
     * @param string $password
     * @return \Base\Entity\Users
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Get the value of password.
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Set the value of status.
     *
     * @param int $status
     * @return \Base\Entity\Users
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get the value of status.
     *
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set the value of created_at.
     *
     * @param \DateTime $created_at
     * @return \Base\Entity\Users
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Get the value of created_at.
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Set the value of updated_at.
     *
     * @param \DateTime $updated_at
     * @return \Base\Entity\Users
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Get the value of updated_at.
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Set AuthRole entity (many to one).
     *
     * @param \Base\Entity\AuthRole $auth_role
     * @return \Base\Entity\Users
     */
    public function setAuthRole($auth_role)
    {
        $this->auth_role = $auth_role;

        return $this;
    }

    /**
     * Get AuthRole entity (many to one).
     *
     * @return \Base\Entity\AuthRole
     */
    public function getAuthRole()
    {
        return $this->auth_role;
    }

    /**
     * Not used, Only defined to be compatible with InputFilterAwareInterface.
     *
     * @param \Laminas\InputFilter\InputFilterInterface $inputFilter
     * @throws \Exception
     */
    public function setInputFilter(InputFilterInterface $inputFilter)
    {
        throw new \Exception("Not used.");
    }

    /**
     * Return a for this entity configured input filter instance.
     *
     * @return InputFilterInterface
     */
    public function getInputFilter()
    {
        if ($this->inputFilter instanceof InputFilterInterface) {
            return $this->inputFilter;
        }
        $factory = new InputFactory();
        $filters = [
            [
                'name' => 'id',
                'required' => false,
                'filters' => [
                                    ['name' => 'Laminas\Filter\ToInt'],
                                ],
                'validators' => [
                                    ['name' => 'Laminas\I18n\Validator\IsInt'],
                                ],
            ],
            [
                'name' => 'auth_role_id',
                'required' => true,
                'filters' => [
                                    ['name' => 'Laminas\Filter\ToInt'],
                                ],
                'validators' => [
                                    ['name' => 'Laminas\I18n\Validator\IsInt'],
                                ],
            ],
            [
                'name' => 'username',
                'required' => true,
                'filters' => [
                                    ['name' => 'Laminas\Filter\StripTags'],
                                    ['name' => 'Laminas\Filter\StringTrim'],
                                ],
                'validators' => [
                                    [
                                        'name' => 'Laminas\Validator\StringLength',
                                        'options' => [
                                            'encoding' => 'UTF-8',
                                            'min' => 1,
                                            'max' => 45
                                        ],
                                    ],
                                ],
            ],
            [
                'name' => 'password',
                'required' => true,
                'filters' => [
                                    ['name' => 'Laminas\Filter\StripTags'],
                                    ['name' => 'Laminas\Filter\StringTrim'],
                                ],
                'validators' => [
                                    [
                                        'name' => 'Laminas\Validator\StringLength',
                                        'options' => [
                                            'encoding' => 'UTF-8',
                                            'min' => 1,
                                            'max' => 45
                                        ],
                                    ],
                                ],
            ],
            [
                'name' => 'status',
                'required' => true,
                'filters' => [
                                    ['name' => 'Laminas\Filter\ToInt'],
                                ],
                'validators' => [
                                    ['name' => 'Laminas\I18n\Validator\IsInt'],
                                ],
            ],
            [
                'name' => 'created_at',
                'required' => false,
                'filters' => [],
                'validators' => [],
            ],
            [
                'name' => 'updated_at',
                'required' => false,
                'filters' => [],
                'validators' => [],
            ],
        ];
        $this->inputFilter = $factory->createInputFilter($filters);

        return $this->inputFilter;
    }

    /**
     * Populate entity with the given data.
     * The set* method will be used to set the data.
     *
     * @param array $data
     * @return boolean
     */
    public function populate(array $data = [])
    {
        foreach ($data as $field => $value) {
            $setter = sprintf('set%s', ucfirst(
                str_replace(' ', '', ucwords(str_replace('_', ' ', $field)))
            ));
            if (method_exists($this, $setter)) {
                $this->{$setter}($value);
            }
        }

        return true;
    }

    /**
     * Return a array with all fields and data.
     * Default the relations will be ignored.
     *
     * @param array $fields
     * @return array
     */
    public function getArrayCopy(array $fields = [])
    {
        $dataFields = ['id', 'auth_role_id', 'username', 'password', 'status', 'created_at', 'updated_at'];
        $relationFields = ['authRole'];
        $copiedFields = [];
        foreach ($relationFields as $relationField) {
            $map = null;
            if (array_key_exists($relationField, $fields)) {
                $map = $fields[$relationField];
                $fields[] = $relationField;
                unset($fields[$relationField]);
            }
            if (!in_array($relationField, $fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $relationField)))));
            $relationEntity = $this->{$getter}();
            $copiedFields[$relationField] = (!is_null($map))
                ? $relationEntity->getArrayCopy($map)
                : $relationEntity->getArrayCopy();
            $fields = array_diff($fields, [$relationField]);
        }
        foreach ($dataFields as $dataField) {
            if (!in_array($dataField, $fields) && !empty($fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $dataField)))));
            $copiedFields[$dataField] = $this->{$getter}();
        }

        return $copiedFields;
    }

    public function __sleep()
    {
        return ['id', 'auth_role_id', 'username', 'password', 'status', 'created_at', 'updated_at'];
    }
}